---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: deploy-fortune
  namespace: newname
  labels:
    app: fortune
    version: v1

spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: pod-fortune
      version: v1
  template: 
    metadata: 
      name: pod-fortune
      labels: 
        app: pod-fortune
        version: v1
    spec:
      containers:
      - name: fortune
        image: stackupiss/fortune:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: httpport
          containerPort: 3000






