---
kind: Namespace
apiVersion: v1
metadata: 
  name: myns
  labels: 
    app: myapp

---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: mydb-svc
  namespace: myns
  labels:
    app: myns
    version: v1

spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: pod-mydb-svc
      version: v1
  template: 
    metadata: 
      name: pod-mydb-svc
      labels: 
        app: pod-mydb-svc
        version: v1
    spec:
      containers:
      - name: mydb-svc
        image: stackupiss/northwind-db:v1
        imagePullPolicy: Always
        ports:
        - name: mysqlport
          containerPort: 3306